//Action Types
const GOT_CAMPUSES_FROM_SERVER = 'GOT_CAMPUSES_FROM_SERVER'
const SELECTED_A_CAMPUS = 'SELECTED_A_CAMPUS'
const UPDATED_A_CAMPUS = 'UPDATED_A_CAMPUS'
const DELETED_A_CAMPUS = 'DELETED_A_CAMPUS'
const CREATE_CAMPUS = 'CREATE_CAMPUS'


//Action Creators

//Thunks
